server:
  port: 8086

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme

logging:
  level:
    org.elasticsearch.client: DEBUG   # Hiển thị log truy vấn Elasticsearch
