version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis-demo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data:
